stages:
  - build
  - test
  - deploy

# Job para ejecutar los tests
run_tests:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17  # Imagen Maven con OpenJDK
  script:
    - mvn clean test  # Ejecutar los tests con Maven
  only:
    - main
    - develop

# Job para la construcción de la imagen Docker
build_image:
  stage: build
  image: docker:cli  # Usamos una imagen con Docker CLI
  services:
    - docker:dind  # Habilitar Docker-in-Docker
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG  # Nombre de la imagen
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY  # Login en el registry Docker
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .  # Construir la imagen Docker
    - docker push "$DOCKER_IMAGE_NAME"  # Subir la imagen al registry Docker
    - |
      # Etiquetado y Push solo si estamos en 'main' o 'develop'
      if [[ "$CI_COMMIT_BRANCH" == "main" || "$CI_COMMIT_BRANCH" == "develop" ]]; then
        # Etiquetar como 'latest' en main y develop
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      
        # Agregar versionado semántico en 'main' (solo en la rama main)
        if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
          VERSION_TAG=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:$VERSION_TAG"
          docker push "$CI_REGISTRY_IMAGE:$VERSION_TAG"
        fi
      fi


  only:
    - main
    - develop
