-- Usuarios
INSERT INTO USER_APP (id) VALUES (1);
INSERT INTO USER_APP (id) VALUES (2);

-- Ítems del carrito, traídos de otra base
INSERT INTO CARD_ITEM (id, PRODUCT_ID, QUANTITY) VALUES (1001, 501, 2);
INSERT INTO CARD_ITEM (id, PRODUCT_ID, QUANTITY) VALUES (1002, 502, 1);

-- Órdenes de entrega (ahora sí podés referenciar por ID fijo)
INSERT INTO DELIVERY_ORDER (
    id, CREATE_TIMESTAMP, PICKED_TIMESTAMP, SELLER_STARTS, PRODUCT_STARTS,
    DELIVERY_STARTS, STATUS, BUYER_ID, DELIVER_ID, CARD_ITEM_ID
) VALUES (
    6622, CURRENT_TIMESTAMP, NULL, NULL, NULL,
    NULL, 'PENDING_ORDER', 1, NULL, 1001
);

INSERT INTO DELIVERY_ORDER (
    id, CREATE_TIMESTAMP, PICKED_TIMESTAMP, SELLER_STARTS, PRODUCT_STARTS,
    DELIVERY_STARTS, STATUS, BUYER_ID, DELIVER_ID, CARD_ITEM_ID
) VALUES (
    44321, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5, 4,
    5, 'DELIVERED_ORDER', 2, 1, 1002
);
